spring:
  profiles.include: oauth
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    show_sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/snowball?&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    timeout: 600
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION


